### ISSUE TITLE
gdb not launch in sublime text 3

### ISSUE THREAD

**Issue by daguniko** [quarnster/SublimeGDB#87]
hi.
I want to try sublimegdb in sublime text 3.
but launch key `F5` is not working.
so, I tried to check whether sublimegdb is working or not use sublime console.
I found this error. and, Im in trouble.
If someone can understand this error, Please reply for me.

```
command: gdb_launch
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "/Users/admin/Library/Application Support/Sublime Text 3/Packages/SublimeGDB/sublimegdb.py", line 1600, in run
    commandline = expand_path(commandline, self.window)
  File "/Users/admin/Library/Application Support/Sublime Text 3/Packages/SublimeGDB/sublimegdb.py", line 102, in expand_path
    value = re.sub(r'\${file}', lambda m: file_name, value)
  File "./re.py", line 170, in sub
TypeError: expected string or buffer
```

**Comment by tamaroth** [comment]
I had the exact same error and it seems that sometimes the value of 'value' is None and it's not accepted as valid parameter for re.sub, I have fixed that with adding small sanity check before that in the form of:

if value is None:
   return value

it removed the python error, but then it was followed by another error, namely:
The directory given does not exist: \tmp

I'm still not sure how to fix this further, but I'll give it a try (I'm not really proficient in either python on Sublime subsystem, but I'll give it a go anyhow).

If someone figures how to fix it properly, let us know!
